# Generated by Django 5.2.12 on 2026-03-09 17:27

from django.db import migrations


def populate_blank_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(email=""):
        user.email = f"{user.username}@placeholder.local"
        user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_unique'),
    ]

    operations = [
        migrations.RunPython(populate_blank_emails, migrations.RunPython.noop),
    ]
